//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModelDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Salary { get; set; }
    }
}
